{
 "title": "Практика 4 Якушев ИВБО-07-21",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"} / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{image!=\"\"}) by (name)\n",
     "legendFormat": "{{container_label_com_docker_compose_project}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\"} / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Использование сети",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Disk read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{image!=\"\"}[5m]) / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{image!=\"\"}[5m]) / 1024 / 1024",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Количество поднятых контейнеров",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}