services:
  cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      hostname: cadvisor
      container_name: cadvisor
      volumes:
        - /:/rootfs:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /cgroup:/cgroup:ro
      ports:
        - "9091:8080"
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    environment: 
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml
      - grafana-storage:/var/lib/grafana
    ports:
      - "9092:3000"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prometheus
    ports:
      - "8080:8080"
    command: ["python3", "app/main.py"]
  
volumes:
  grafana-storage: