global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'python-project'
    static_configs:
      - targets:
        - app:8000 
rule_files:
  - "rules.yml"